# Generated by Django 3.2.4 on 2021-06-30 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hmrxapp', '0002_altera_tam_histograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtragem',
            name='data_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 22, 35, 52, 720228, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='filtragem',
            name='histograma',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
